spring:
  application:
    name: human resources management system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/HRMS-DB
    username: root
    password: password
  messages:
    basename: messages
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true